# Numpy

In [2]:
import numpy as np

In [3]:
arr_2 = np.array([[  1,   2,   3],
                  [  4,   5,   6],
                  [ 10,  20,  30],
                  [ 40,  50,  60],
                  [100, 200, 300],
                  [400, 500, 600]])
arr_2.shape

(6, 3)

Expand dimensions:

In [4]:
arr_2[np.newaxis, :, :] == \
    np.expand_dims(arr_2, 0)  # insert new axis at index in shape tuple

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]], dtype=bool)

In [5]:
arr_2.reshape(-1, 2)

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [100, 200],
       [300, 400],
       [500, 600]])

In [6]:
arr_2[np.newaxis, :3 , :2]

array([[[ 1,  2],
        [ 4,  5],
        [10, 20]]])

In [7]:
arr_3 = np.vstack((arr_2[np.newaxis, :3],
                   arr_2[np.newaxis, 3:]))

arr_3 == np.concatenate((arr_2[np.newaxis, :3],
                         arr_2[np.newaxis, 3:]), axis=0)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]], dtype=bool)

# Collinearity 

In [1]:
import sys
import itertools as it
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display



In [8]:
X_lm = np.random.rand(10, 3)
X_lm[:, 0] += 2


X_nlm = X_lm


X_nlm

array([[ 2.95244664,  0.47933905,  0.15764358],
       [ 2.9784175 ,  0.17931798,  0.15465279],
       [ 2.19906374,  0.60435913,  0.29323482],
       [ 2.12078749,  0.56757786,  0.2686449 ],
       [ 2.7756924 ,  0.52621938,  0.50958959],
       [ 2.08123161,  0.27501465,  0.1456011 ],
       [ 2.12736401,  0.08367018,  0.65216633],
       [ 2.93672992,  0.9234749 ,  0.08922432],
       [ 2.6471937 ,  0.52757072,  0.39324379],
       [ 2.44875801,  0.06299593,  0.0184691 ]])

TypeError: Required argument 'object' (pos 1) not found

In [ ]:
X 